// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB39h1evJPq05yhvD56hhA7be7QSouP6rk',
    appId: '1:837770748123:web:54410c5f79f2b6cb86acfe',
    messagingSenderId: '837770748123',
    projectId: 'buzzchat-chat-app',
    authDomain: 'buzzchat-chat-app.firebaseapp.com',
    storageBucket: 'buzzchat-chat-app.firebasestorage.app',
    measurementId: 'G-H1TDN8TS81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB36hbP9JRTOdnwfDvztRTTphpXbgWS5A',
    appId: '1:837770748123:android:91c5cb1f84c1632786acfe',
    messagingSenderId: '837770748123',
    projectId: 'buzzchat-chat-app',
    storageBucket: 'buzzchat-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwP-N8zhXBOT2KYNxFdM7KnzbvF7nFXLc',
    appId: '1:837770748123:ios:3e31aada76d76c9286acfe',
    messagingSenderId: '837770748123',
    projectId: 'buzzchat-chat-app',
    storageBucket: 'buzzchat-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.buzzchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwP-N8zhXBOT2KYNxFdM7KnzbvF7nFXLc',
    appId: '1:837770748123:ios:3e31aada76d76c9286acfe',
    messagingSenderId: '837770748123',
    projectId: 'buzzchat-chat-app',
    storageBucket: 'buzzchat-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.buzzchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB39h1evJPq05yhvD56hhA7be7QSouP6rk',
    appId: '1:837770748123:web:b60eabc12c323bca86acfe',
    messagingSenderId: '837770748123',
    projectId: 'buzzchat-chat-app',
    authDomain: 'buzzchat-chat-app.firebaseapp.com',
    storageBucket: 'buzzchat-chat-app.firebasestorage.app',
    measurementId: 'G-G142C5T1RG',
  );
}
